### ISSUE TITLE
FizzBuzz

### ISSUE THREAD

**Issue by l-e-f** [Kaitieloo/Learning#1]
Can you write me a function that takes an integer (N >1) as an argument and print all integers one-to-N, but print “Fizz” if an integer is divisible by three, “Buzz” if an integer is divisible by five, and “FizzBuzz” if an integer is divisible by both three and five?

**Comment by Kaitieloo** [comment]
I could. 

And I will.

**Comment by Kaitieloo** [comment]
Completed. Check master.
